### ISSUE TITLE
Save cover pic error

### ISSUE THREAD

**Issue by chenui** [janeczku/calibre-web#1829]
After update to 0.6.10, when fectch metadata, page appeared wrong message, I don't understand what that meaning, it seems like "'Response' object has no attribute 'save'". I tried save cover from local, the error still appear. If I clear  "Fetch Cover from URL" box blank, I can save the metadata normally.

**To Reproduce**
1. Go to 'Edit metadata'
2. Click on 'fetch metadata'
3. See error

**Logfile**
Traceback (most recent call last):
  File "/root/git/calibre-web/cps/helper.py", line 582, in save_cover_from_url
    return save_cover(img, book_path)
  File "/root/git/calibre-web/cps/helper.py", line 649, in save_cover
    return save_cover_from_filestorage(os.path.join(config.config_calibre_dir, book_path), "cover.jpg", img)
  File "/root/git/calibre-web/cps/helper.py", line 606, in save_cover_from_filestorage
    img.save(os.path.join(filepath, saved_filename))
AttributeError: 'Response' object has no attribute 'save'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/git/calibre-web/cps/editbooks.py", line 689, in edit_book
    result, error = helper.save_cover_from_url(to_save["cover_url"], book.path)
  File "/root/git/calibre-web/cps/helper.py", line 588, in save_cover_from_url
    except MissingDelegateError as ex:
NameError: name 'MissingDelegateError' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/git/calibre-web/vendor/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/git/calibre-web/vendor/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/git/calibre-web/vendor/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/git/calibre-web/vendor/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/git/calibre-web/vendor/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/git/calibre-web/vendor/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/git/calibre-web/cps/usermanagement.py", line 38, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/root/git/calibre-web/vendor/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/root/git/calibre-web/cps/editbooks.py", line 66, in inner
    return f(*args, **kwargs)
  File "/root/git/calibre-web/cps/editbooks.py", line 750, in edit_book
    log.debug_or_exception(e)
  File "/root/git/calibre-web/cps/logger.py", line 51, in debug_or_exception
    self.error(message, stacklevel=2, *args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'stacklevel'
[2021-01-26 01:02:27,347]  INFO {cps.admin:1267} Update status requested

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6792146/105785339-9b0d6e00-5fb5-11eb-8395-464d52b9c1d3.png)

**Environment (please complete the following information):**
 - OS: Debian
 - Python version: python3.7
 - Calibre-Web version:  0.6.10
 - Docker container: None
 - Special Hardware: 
 - Browser:Chrome 88, Safari 14

**Comment by OzzieIsaacs** [comment]
I can't reproduce this, for me it's working
Did you install wand (visible in about section)?

**Comment by chenui** [comment]
Now I can upload cover from local drive, but still error from the url.
