### ISSUE TITLE
Calibre-web doesn't work with flask-babel 3.0

### ISSUE THREAD

**Issue by jvoisin** [janeczku/calibre-web#2674]
According to the release notes of [flask babel 3.0]( https://github.com/python-babel/flask-babel/releases/tag/v3.0.0 ):

> Babel.locale_selector and Babel.timezone_selector no longer exist. They must be provided
either when the Babel() object is created or when init_app() is called. This is to support
having a single Babel object for multiple Flask apps (https://github.com/python-babel/flask-babel/issues/107) as well as to simplify settings
and multi-threaded state.

Unfortunately, `Babel.locale_selector` is used by calibre-web, and thus is crashing at startup:

```
Traceback (most recent call last):
  File "/opt/calibre/cps.py", line 28, in <module>
    from cps.main import main
  File "/opt/calibre/cps/__init__.py", line 39, in <module>
    from .babel import babel
  File "/opt/calibre/cps/babel.py", line 13, in <module>
    @babel.localeselector
     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Babel' object has no attribute 'localeselector'
```

**Comment by OzzieIsaacs** [comment]
Please update to the newest nightly. By the way: the versions are pinned to a maximum version to exactly avoid trouble like this

**Comment by MrMxyzptlk** [comment]
I have the latest 0.6.20
Python 3.10 and am still getting this error?

C:\calibre-web>"c:\Program Files\Python310\python.exe" cps.py -p appmagazines.db
Traceback (most recent call last):
  File "C:\calibre-web\cps.py", line 28, in <module>
    from cps.main import main
  File "C:\calibre-web\cps\__init__.py", line 39, in <module>
    from .babel import babel
  File "C:\calibre-web\cps\babel.py", line 13, in <module>
    @babel.localeselector
AttributeError: 'Babel' object has no attribute 'localeselector'

Thanks
