### ISSUE TITLE
Broken UI after upgrading to 0.6.6

### ISSUE THREAD

**Issue by adilei** [janeczku/calibre-web#1265]
After upgrading to 0.6.6, the UI seems broken (see image attached) and there are some client side errors. 

Client side errors (F12) are:

Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.1.12:8083/static/css/style.css?q=80610f2".
192.168.1.12/:17 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.1.12:8083/static/css/caliBlur.min.css?q=9fd6e9a".
192.168.1.12/:15 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.1.12:8083/static/css/upload.css?q=0b3211d".
main.js?q=1c4127b:1 Uncaught SyntaxError: Unexpected token '<'
uploadprogress.js?q=c39b0fa:1 Uncaught SyntaxError: Unexpected token '<'
caliBlur.js?q=be94811:1 Uncaught SyntaxError: Unexpected token '<'
jquery.min.js?q=4b57cf4:2 jQuery.Deferred exception: $(...).uploadprogress is not a function TypeError: $(...).uploadprogress is not a function
    at HTMLDocument.<anonymous> (http://192.168.1.12:8083/rated/new/:3075:31)
    at l (http://192.168.1.12:8083/static/js/libs/jquery.min.js?q=4b57cf4:2:29375)
    at c (http://192.168.1.12:8083/static/js/libs/jquery.min.js?q=4b57cf4:2:29677) undefined
w.Deferred.exceptionHook @ jquery.min.js?q=4b57cf4:2
c @ jquery.min.js?q=4b57cf4:2
setTimeout (async)
(anonymous) @ jquery.min.js?q=4b57cf4:2
u @ jquery.min.js?q=4b57cf4:2
fireWith @ jquery.min.js?q=4b57cf4:2
fire @ jquery.min.js?q=4b57cf4:2
u @ jquery.min.js?q=4b57cf4:2
fireWith @ jquery.min.js?q=4b57cf4:2
ready @ jquery.min.js?q=4b57cf4:2
_ @ jquery.min.js?q=4b57cf4:2
jquery.min.js?q=4b57cf4:2 Uncaught TypeError: $(...).uploadprogress is not a function
    at HTMLDocument.<anonymous> ((index):3075)
    at l (jquery.min.js?q=4b57cf4:2)
    at c (jquery.min.js?q=4b57cf4:2)
(anonymous) @ (index):3075
l @ jquery.min.js?q=4b57cf4:2
c @ jquery.min.js?q=4b57cf4:2
setTimeout (async)
w.readyException @ jquery.min.js?q=4b57cf4:2
(anonymous) @ jquery.min.js?q=4b57cf4:2
l @ jquery.min.js?q=4b57cf4:2
c @ jquery.min.js?q=4b57cf4:2
setTimeout (async)
(anonymous) @ jquery.min.js?q=4b57cf4:2
u @ jquery.min.js?q=4b57cf4:2
fireWith @ jquery.min.js?q=4b57cf4:2
fire @ jquery.min.js?q=4b57cf4:2
u @ jquery.min.js?q=4b57cf4:2
fireWith @ jquery.min.js?q=4b57cf4:2
c @ jquery.min.js?q=4b57cf4:2
setTimeout (async)
(anonymous) @ jquery.min.js?q=4b57cf4:2
u @ jquery.min.js?q=4b57cf4:2
fireWith @ jquery.min.js?q=4b57cf4:2
fire @ jquery.min.js?q=4b57cf4:2
u @ jquery.min.js?q=4b57cf4:2
fireWith @ jquery.min.js?q=4b57cf4:2
ready @ jquery.min.js?q=4b57cf4:2
_ @ jquery.min.js?q=4b57cf4:2﻿
​
Debug log is not showing anything.

I tried cloning a fresh installation - same result.

Thanks in advance.

![image](https://user-images.githubusercontent.com/28257760/77234158-f4965680-6bb4-11ea-87a8-9e534c2c0689.png)

**Comment by OzzieIsaacs** [comment]
please check for the hints in #999

**Comment by OzzieIsaacs** [comment]
Or maybe the solution form #1155 fits to your problem

**Comment by adilei** [comment]
Thanks, will give those suggestions a try

**Comment by adilei** [comment]
Fixed after changing to Python 3.6 instead of 2.7. 

Thanks!
