### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by CorvusGei** [janeczku/calibre-web#2737]
After updating to the new version via the web interface I can't reach calibre-web anymore, even after a reboot.
How could I fix this or does anyone have the same problem?
Hardware: Rasperry Pi 4B, 8GB
I had Calibre-Web running on Port 8083.
Thanks

**Comment by CorvusGei** [comment]
*** "flask-limiter" is needed for calibre-web to run. Please install it using pip: "pip install flask-limiter" ***
pip install flask-limiter
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
calibreweb 0.6.18 requires Flask<2.1.0,>=1.0.2, but you have flask 2.2.3 which is incompatible.
calibreweb 0.6.18 requires werkzeug<2.1.0, but you have werkzeug 2.2.3 which is incompatible.

**Comment by OzzieIsaacs** [comment]
I‘m not sure where exactly the messages the the 2nd post come from and how you installed calibreweb.
A pip install calibreweb=0.6.20 could help

**Comment by CorvusGei** [comment]
I tried `pip install calibreweb==0.6.20` and could run it.
But after updating I was logged out everytime I  set my library source directory.
Then I tried to use the docker image - the same problem.
Maybe it's because my NAS with the library was/is on fully load because of other operations and calibreweb couldn't reach it? I don't know, I'll try later when the operations are finished. But I should not get logged out after entering the path and confirming. Problem appears locally with pip install and with the docker container.

**Comment by jagalile** [comment]
I have a similar issue,.

After update to 0.6.20 via web my calibre web crash now I'm trying to launch again with `python3 cps.py` and I'm getting this error

`*** "flask-limiter" is needed for calibre-web to run. Please install it using pip: "pip install flask-limiter" ***`

But I have flask-limiter installed
`Flask-Limiter                 3.3.0`

**Comment by OzzieIsaacs** [comment]
@jagalile Please make sure you installed flask-limiter in the same virtual environment (or systemwide) in which calibre-web is running. If it's not detected than it's not installed in the corresponding virtual environment. If you are using docker, please ask the docker provider for help.

**Comment by mirino75** [comment]
The same error after I clicked to update to 0.6.20.
Everything was OK before.

HW: Synology NAS 720+ (DSM 7.1.1-42962 Update 5)
SW: Docker 20.10.3-1308

**Comment by OzzieIsaacs** [comment]
@mirino75 
> ImportError: cannot import name 'CronTrigger' from 'cps.services.background_scheduler' (/calibre-web/app/cps/services/background_scheduler.py)`

APScheduler isn't properly installed in the docker container, please ask the docker provider for help

**Comment by CorvusGei** [comment]
I tried to install it new with the virtual environment from the manual and can't login into calibre-web.
The Docker image seems to be too big for a tool like calibre-web to give it a try. So I'll think I have to look after a different solution for hosting a web interface for my calibre library.

**Comment by bmn001** [comment]
Thanks for this.  Updating from 0.6.19 to 0.6.20 got me the CronTrigger error, and I'm not even using Docker.

```pip3 install apscheduler``` and a restart fixed it.

**Comment by decaba** [comment]
> Thanks for this. Updating from 0.6.19 to 0.6.20 got me the CronTrigger error, and I'm not even using Docker.
> 
> `pip3 install apscheduler` and a restart fixed it.

Installing apscheduler and restarting fixed it for me as well.

**Comment by yongfanbeta** [comment]
if you run calibre-web in docker, install module in docker bash
```bash
pip install flask-limiter
pip install apscheduler
```
and restart the docker
